"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "tokyo_night_storm"

[palettes.tokyo_night_storm]
fg = "#c0caf5"
bg = "#24283b"
blue = "#7aa2f7"
cyan = "#7dcfff"
purple = "#bb9af7"
green = "#9ece6a"
yellow = "#e0af68"
red = "#f7768e"
muted = "#565f89"
comment = "#a9b1d6"

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold purple)"

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"local" = " "

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold red"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "="
up_to_date = ""
untracked = "?"
stashed = '\$'
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[cmd_duration]
min_time = 2000
format = "took [$duration](bold yellow) "

[username]
style_user = "bold cyan"
style_root = "bold red"
format = "[$user]($style) "
show_always = false

[hostname]
ssh_only = true
style = "bold green"
format = "at [$hostname]($style) "
